# Generated by Django 4.2.2 on 2023-07-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='invoice_id',
            new_name='order_id',
        ),
    ]
