# Generated by Django 4.2.2 on 2023-07-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_invoice_id_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='razorpay_order_id',
        ),
    ]
